version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: dotnet restore src
build_script:
  - cmd: dotnet build src\ --configuration Release -p:Version=%APPVEYOR_BUILD_VERSION%
test_script:
- cmd: dotnet test src\MethodBoundaryAspect.Fody.UnitTests.NetFramework --configuration Release
- cmd: dotnet test src\MethodBoundaryAspect.Fody.UnitTests.NetCore --configuration Release
artifacts:
- path: src\MethodBoundaryAspect.Fody\bin\$(configuration)
  name: Binaries
- path: 'src\**\*.nupkg'
  name: Packages
deploy:
- provider: NuGet
  api_key:
    secure: qP4lObisvUwAbvxVFPtBwaTC25bTgpJA8MaQu7xXqZS09uosIhhdaxrW2znYzOCQ
  skip_symbols: true
  on:
    branch: master